#!/bin/bash

# Script to automatically detect and configure Android SDK path
# This ensures local.properties works for all developers without manual configuration

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ANDROID_DIR="$PROJECT_ROOT/android"
LOCAL_PROPERTIES="$ANDROID_DIR/local.properties"

echo "🔍 Detecting Android SDK location..."

# Try multiple common locations
SDK_PATHS=(
    "$ANDROID_HOME"
    "$ANDROID_SDK_ROOT"
    "$HOME/Library/Android/sdk"
    "$HOME/.android/sdk"
    "$HOME/Android/Sdk"
    "/opt/android-sdk"
    "/usr/local/android-sdk"
)

SDK_PATH=""

# Find first valid SDK path
for path in "${SDK_PATHS[@]}"; do
    if [ -n "$path" ] && [ -d "$path" ] && [ -d "$path/platform-tools" ]; then
        SDK_PATH="$path"
        echo "✅ Found Android SDK at: $SDK_PATH"
        break
    fi
done

# If not found, prompt user
if [ -z "$SDK_PATH" ]; then
    echo "❌ Could not automatically detect Android SDK location."
    echo ""
    echo "Please provide your Android SDK path (or press Enter to skip):"
    read -r SDK_PATH
    
    if [ -z "$SDK_PATH" ]; then
        echo "⚠️  Skipping SDK configuration. You'll need to create android/local.properties manually."
        exit 0
    fi
    
    if [ ! -d "$SDK_PATH" ]; then
        echo "❌ Error: SDK path does not exist: $SDK_PATH"
        exit 1
    fi
fi

# Create local.properties
cat > "$LOCAL_PROPERTIES" << EOF
## This file is automatically generated by setup-android-sdk.sh
# Do not modify this file manually -- it will be regenerated.
# This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
sdk.dir=$SDK_PATH
EOF

echo "✅ Created $LOCAL_PROPERTIES"
echo "✅ Android SDK configured successfully!"
echo ""
echo "You can now run: npx expo run:android"

